### ISSUE TITLE
MEMORY LEAKS?

### ISSUE THREAD

**Issue by pheonixfirewingz** [pheonixfirewingz/LunaLuxEngine#3]
Exception thrown at 0x00007FFB30F6A839 in TestGame.exe: Microsoft C++ exception: _com_error at memory location 0x000000E8120FFB80.

**Comment by dudeisbrendan03** [comment]
![paint](https://user-images.githubusercontent.com/6009600/74442538-936abd00-4e69-11ea-871e-c40a3b872ab2.png)
That's a thicc title you've got there

**Comment by dudeisbrendan03** [comment]
Also how and why am I a contributor?

**Comment by dudeisbrendan03** [comment]
If you send me your PC specs I can work on a seamless Hackintosh drive for you

**Comment by pheonixfirewingz** [comment]
Idk how to fix this

**Comment by dudeisbrendan03** [comment]
What do you develop the project on? Visual Studio?

**Comment by pheonixfirewingz** [comment]
visual studio and CMake on windows

**Comment by dudeisbrendan03** [comment]
Maybe later.

Call me or something.

**Comment by pheonixfirewingz** [comment]
i tracked the memory leak here but idk why it is leaking 

`D3D11_BUFFER_DESC bd;
	ZeroMemory(&bd, sizeof(bd));
	bd.Usage = D3D11_USAGE_DYNAMIC;                // write access access by CPU and GPU
	bd.ByteWidth = sizeof(VERTEX) * 3;             // size is the VERTEX struct * 3
	bd.BindFlags = D3D11_BIND_VERTEX_BUFFER;       // use as a vertex buffer
	bd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;    // allow CPU to write in buffer

	dev->CreateBuffer(&bd, nullptr, &pVBuffer);       // create the buffer

	// copy the vertices into the buffer
	D3D11_MAPPED_SUBRESOURCE ms;
	devcon->Map(pVBuffer, NULL, D3D11_MAP_WRITE_DISCARD, NULL, &ms);    // map the buffer
	memcpy(ms.pData, OurVertices, sizeof(OurVertices));                 // copy the data
	devcon->Unmap(pVBuffer, NULL);`

**Comment by dudeisbrendan03** [comment]
```c++
D3D11_BUFFER_DESC bd;
ZeroMemory(&bd, sizeof(bd));
bd.Usage = D3D11_USAGE_DYNAMIC; // write access access by CPU and GPU
bd.ByteWidth = sizeof(VERTEX) * 3; // size is the VERTEX struct * 3
bd.BindFlags = D3D11_BIND_VERTEX_BUFFER; // use as a vertex buffer
bd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE; // allow CPU to write in buffer

dev->CreateBuffer(&bd, nullptr, &pVBuffer);       // create the buffer

// copy the vertices into the buffer
D3D11_MAPPED_SUBRESOURCE ms;
devcon->Map(pVBuffer, NULL, D3D11_MAP_WRITE_DISCARD, NULL, &ms);    // map the buffer
memcpy(ms.pData, OurVertices, sizeof(OurVertices));                 // copy the data
devcon->Unmap(pVBuffer, NULL);```
